import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, ClipboardCheck, Pill, Brain, FileText, ShieldAlert, HeartPulse, FlaskConical, Star, StarOff } from 'lucide-react';
import './style.css';

const meds = [
  {name:'Clozapine',class:'Atypical antipsychotic',category:'Antipsychotic',tags:['REMS','ANC','metabolic','seizure risk','constipation'],pearls:['Reserve for treatment-resistant schizophrenia or recurrent suicidal behavior in schizophrenia/schizoaffective disorder.','ANC monitoring is essential; confirm current REMS/facility process before dispensing.','Major risks: agranulocytosis, myocarditis, seizures, severe constipation/ileus, orthostasis, sedation, metabolic effects.','Smoking changes can alter levels; stopping smoking may increase clozapine exposure.'],monitoring:['ANC','A1c/glucose','lipids','weight/BMI','bowel function','sedation/orthostasis','HR/chest pain/fever early in therapy'],redFlags:['fever','chest pain','severe constipation','syncope','seizure','ANC issue'],note:'Recommend verifying ANC eligibility and bowel regimen, and monitoring for sedation, orthostasis, metabolic effects, and signs of myocarditis during early therapy.'},
  {name:'Lithium',class:'Mood stabilizer',category:'Mood Stabilizer',tags:['level','renal','thyroid','toxicity'],pearls:['Narrow therapeutic index; levels must be interpreted with timing and clinical status.','Toxicity risk increases with dehydration, renal impairment, NSAIDs, ACE inhibitors/ARBs, and some diuretics.','Assess tremor, GI symptoms, confusion, ataxia, polyuria/polydipsia.'],monitoring:['Lithium level','SCr/eGFR','TSH','calcium','pregnancy status when relevant','hydration/sodium intake','drug interactions'],redFlags:['ataxia','confusion','vomiting/diarrhea','new NSAID','AKI/dehydration'],note:'Recommend checking lithium level with renal and thyroid monitoring, reviewing interacting medications, and assessing for clinical signs of lithium toxicity.'},
  {name:'Valproate / Divalproex',class:'Mood stabilizer / anticonvulsant',category:'Mood Stabilizer',tags:['level','LFT','platelets','teratogenicity'],pearls:['Commonly used for bipolar mania and agitation-related mood instability.','Watch for hepatotoxicity, pancreatitis, thrombocytopenia, sedation, tremor, weight gain.','High-risk in pregnancy; confirm facility policy for counseling/documentation.'],monitoring:['Valproate level','LFTs','CBC/platelets','weight','sedation','tremor','pregnancy considerations'],redFlags:['abdominal pain','marked sedation','platelet drop','LFT elevation','pregnancy risk'],note:'Recommend valproate level, LFTs, CBC/platelets, and assessment for sedation, tremor, weight gain, and pregnancy-related risk where applicable.'},
  {name:'Carbamazepine',class:'Mood stabilizer / anticonvulsant',category:'Mood Stabilizer',tags:['CYP inducer','CBC','LFT','sodium','rash'],pearls:['Major interaction burden due to enzyme induction.','Watch for rash, hyponatremia, hepatotoxicity, blood dyscrasias, and CNS effects.','Medication reconciliation is especially important when added or stopped.'],monitoring:['CBC','LFTs','sodium','drug interactions','rash','sedation/dizziness','level if clinically indicated'],redFlags:['rash','fever','sore throat','low sodium','interaction cascade'],note:'Recommend CBC, LFTs, sodium monitoring, and a focused interaction review due to carbamazepine enzyme induction and safety risks.'},
  {name:'Lamotrigine',class:'Mood stabilizer / anticonvulsant',category:'Mood Stabilizer',tags:['rash','SJS','slow titration','valproate interaction'],pearls:['Requires slow titration to reduce serious rash risk.','Valproate substantially affects lamotrigine dosing/titration strategy.','If several doses are missed, restart/titration rules may apply per policy and labeling.'],monitoring:['rash','titration schedule','missed doses','valproate interaction','patient education'],redFlags:['rash','mucosal lesions','fever','recent restart','rapid titration'],note:'Recommend confirming lamotrigine titration schedule, missed-dose history, and rash monitoring, especially with concurrent valproate or recent interruption.'},
  {name:'Haloperidol',class:'Typical antipsychotic',category:'Antipsychotic',tags:['EPS','QT','agitation','NMS'],pearls:['Useful for acute agitation but higher EPS risk than many atypicals.','Assess cumulative antipsychotic burden when scheduled and PRN agents overlap.','QT risk increases with high doses, electrolyte abnormalities, and other QT-prolonging drugs.'],monitoring:['EPS','akathisia','QT/EKG risk','K/Mg','sedation','NMS symptoms','duplicate antipsychotics'],redFlags:['rigidity/fever','new dystonia','high QT burden','frequent PRN use','low K/Mg'],note:'Recommend evaluating EPS and QT risk, especially with high cumulative antipsychotic exposure, electrolyte abnormalities, or concurrent QT-prolonging medications.'},
  {name:'Risperidone',class:'Atypical antipsychotic',category:'Antipsychotic',tags:['prolactin','EPS','LAI','metabolic'],pearls:['Dose-related EPS and prolactin effects can occur.','Review renal function for dosing considerations.','May be used orally or as LAI depending on formulation and facility protocol.'],monitoring:['EPS','prolactin symptoms','A1c/glucose','lipids','weight/BMI','renal function','adherence'],redFlags:['galactorrhea','sexual dysfunction','EPS','renal impairment','LAI timing issue'],note:'Recommend monitoring for EPS, prolactin-related adverse effects, metabolic parameters, and renal-dose considerations.'},
  {name:'Paliperidone LAI',class:'Atypical antipsychotic LAI',category:'LAI',tags:['LAI','renal','prolactin','metabolic','missed dose'],pearls:['Confirm exact LAI product because monthly, 3-month, and 6-month products have different rules.','Renal function matters for paliperidone dosing/product suitability.','Verify last injection date, site, dose, and loading/maintenance status.'],monitoring:['last injection date','dose/product','renal function','EPS','prolactin symptoms','metabolic labs','missed-dose protocol'],redFlags:['unknown last dose','wrong product interval','renal impairment','missed loading dose'],note:'Recommend verifying paliperidone LAI product, last injection date, renal function, and missed-dose/loading requirements before administration.'},
  {name:'Aripiprazole LAI',class:'Atypical antipsychotic LAI',category:'LAI',tags:['LAI','oral overlap','akathisia','missed dose'],pearls:['Confirm exact LAI product because initiation and oral overlap requirements differ.','Akathisia can be clinically significant and may look like anxiety/agitation.','Verify last injection date and missed-dose instructions.'],monitoring:['last injection date','oral overlap','akathisia','activation/insomnia','metabolic labs','missed-dose protocol'],redFlags:['no oral overlap when required','severe akathisia','unclear product','missed dose'],note:'Recommend confirming aripiprazole LAI product, oral overlap requirement, last injection date, and monitoring for akathisia or activation.'},
  {name:'Olanzapine',class:'Atypical antipsychotic',category:'Antipsychotic',tags:['metabolic','sedation','weight','agitation'],pearls:['High metabolic risk; weight gain and sedation are common concerns.','Avoid combining IM olanzapine with parenteral benzodiazepines unless facility policy specifically permits and monitoring is in place.','Useful in agitation but cumulative sedation burden matters.'],monitoring:['A1c/glucose','lipids','weight/BMI','sedation','orthostasis','anticholinergic burden','duplicate CNS depressants'],redFlags:['excessive sedation','IM benzo overlap','rapid weight gain','orthostasis','fall risk'],note:'Recommend metabolic monitoring and assessment of sedation/orthostasis, especially when used with other CNS depressants or anticholinergic medications.'},
  {name:'Quetiapine',class:'Atypical antipsychotic',category:'Antipsychotic',tags:['sedation','orthostasis','metabolic','QT'],pearls:['Sedation and orthostasis are frequent limiting effects.','Low-dose use for sleep should be reviewed for risk/benefit.','Consider fall risk and additive CNS depression.'],monitoring:['sedation','orthostasis','falls','A1c/glucose','lipids','weight/BMI','QT risk'],redFlags:['falls','excessive sedation','orthostasis','low-dose sleep-only use','QT burden'],note:'Recommend assessing sedation, orthostasis, fall risk, metabolic monitoring, and whether low-dose use for sleep remains clinically justified.'},
  {name:'Sertraline',class:'SSRI antidepressant',category:'Antidepressant',tags:['SSRI','serotonin','GI','bleeding'],pearls:['Common SSRI option for depression, anxiety, PTSD, and related disorders.','Watch for GI upset, activation, sexual dysfunction, hyponatremia risk, and bleeding risk with NSAIDs/anticoagulants.','Assess for serotonin syndrome risk when combined with serotonergic agents.'],monitoring:['mood/suicidality early','GI effects','activation/insomnia','sodium risk','bleeding risk','serotonergic combinations'],redFlags:['serotonin syndrome symptoms','mania activation','bleeding risk','hyponatremia risk'],note:'Recommend monitoring for activation, GI effects, bleeding risk, hyponatremia risk, and serotonergic drug combinations.'},
  {name:'Venlafaxine / Desvenlafaxine',class:'SNRI antidepressant',category:'Antidepressant',tags:['SNRI','BP','withdrawal','serotonin'],pearls:['Blood pressure effects can be dose-related.','Discontinuation symptoms may be significant if abruptly stopped.','Review serotonergic combinations and activation/mania risk.'],monitoring:['blood pressure','withdrawal symptoms','activation/mania','serotonergic combinations','renal function for desvenlafaxine'],redFlags:['uncontrolled BP','abrupt stop','mania','serotonin syndrome symptoms'],note:'Recommend monitoring blood pressure, discontinuation risk, activation/mania symptoms, and serotonergic drug combinations with SNRI therapy.'},
  {name:'Trazodone',class:'Serotonergic antidepressant / hypnotic use',category:'Sleep/Anxiety',tags:['sedation','orthostasis','priapism','QT'],pearls:['Often used for sleep in behavioral health settings.','Additive sedation and orthostasis matter, especially with antipsychotics, benzodiazepines, and antihypertensives.','Rare priapism counseling may be clinically relevant.'],monitoring:['sedation','orthostasis','falls','QT risk','serotonergic combinations','priapism warning'],redFlags:['falls','syncope','QT burden','priapism','excessive sedation'],note:'Recommend reviewing sedation, orthostasis, fall risk, QT burden, and serotonergic overlap when trazodone is used for sleep.'},
  {name:'Hydroxyzine',class:'Antihistamine anxiolytic',category:'Sleep/Anxiety',tags:['sedation','anticholinergic','QT','PRN'],pearls:['Common non-benzodiazepine PRN for anxiety/insomnia.','Watch additive sedation and anticholinergic burden.','QT risk can matter when combined with other QT-prolonging medications.'],monitoring:['sedation','anticholinergic burden','QT risk','falls','PRN frequency'],redFlags:['excessive PRN use','falls','QT burden','urinary retention/confusion'],note:'Recommend reviewing hydroxyzine PRN frequency, sedation, anticholinergic burden, fall risk, and cumulative QT risk.'},
  {name:'Lorazepam',class:'Benzodiazepine',category:'Detox/PRN',tags:['sedation','falls','withdrawal','respiratory depression'],pearls:['Commonly used for acute agitation, catatonia, anxiety, and alcohol withdrawal protocols.','Additive sedation with antipsychotics, opioids, gabapentinoids, and other CNS depressants is important.','Monitor PRN frequency and taper/withdrawal concerns.'],monitoring:['sedation','respiratory status','falls','PRN frequency','withdrawal protocol','CNS depressant burden'],redFlags:['respiratory depression','falls','delirium','opioid combination','escalating PRN use'],note:'Recommend assessing lorazepam indication, PRN frequency, sedation/respiratory risk, fall risk, and cumulative CNS depressant burden.'},
  {name:'Buprenorphine / Naloxone',class:'Medication for opioid use disorder',category:'Substance Use',tags:['OUD','withdrawal','respiratory depression','diversion'],pearls:['Verify indication, dose, last use, withdrawal status, and continuation plan.','Watch additive CNS/respiratory depression with benzodiazepines, alcohol, and other sedatives.','Ensure discharge continuity and access planning when possible.'],monitoring:['withdrawal symptoms','sedation/respiratory status','adherence','diversion precautions per policy','drug interactions','discharge supply/access'],redFlags:['excess sedation','benzo/alcohol overlap','precipitated withdrawal concern','unclear home dose'],note:'Recommend verifying buprenorphine dose and withdrawal status, monitoring sedation/respiratory risk, and planning for continuity at discharge.'},
  {name:'Naltrexone',class:'Medication for alcohol/opioid use disorder',category:'Substance Use',tags:['AUD','OUD','LFT','opioid-free'],pearls:['Confirm opioid-free status before use for OUD to avoid precipitated withdrawal.','Review hepatic status and LFT monitoring per protocol.','For AUD, assess adherence and whether LAI formulation is appropriate.'],monitoring:['opioid-free status','LFTs','pain/opioid needs','adherence','AUD/OUD indication'],redFlags:['recent opioid use','acute hepatitis concern','need for opioid analgesia','precipitated withdrawal risk'],note:'Recommend confirming opioid-free status and indication before naltrexone, reviewing LFTs/hepatic status, and considering pain-management implications.'}
];
const categories = ['All','Antipsychotic','Mood Stabilizer','LAI','Antidepressant','Sleep/Anxiety','Detox/PRN','Substance Use'];

const checklists = [
  {title:'Daily Behavioral Health Pharmacy Review',icon:ClipboardCheck,items:['Any new starts, dose increases, or high-risk PRNs?','Duplicate antipsychotics or overlapping scheduled + PRN therapy?','QT risk: multiple QT drugs, low K/Mg, cardiac history, high-dose antipsychotic?','Metabolic monitoring needed: weight/BMI, glucose/A1c, lipids?','EPS/akathisia monitoring needed?','Sedation, fall risk, orthostasis, anticholinergic burden?','Renal/hepatic dose issues?','Clozapine, lithium, valproate, carbamazepine, LAI, or detox protocol concerns?','Controlled substance duplication, withdrawal risk, or taper issue?','Clear pharmacist recommendation documented?']},
  {title:'Clozapine Safety Checklist',icon:ShieldAlert,items:['ANC eligibility verified per current facility/REMS process','Baseline/current CBC with ANC reviewed','Bowel regimen or constipation monitoring addressed','Smoking status reviewed','Sedation/orthostasis risk reviewed','Metabolic labs reviewed or recommended','Early myocarditis warning signs monitored: fever, chest pain, tachycardia, dyspnea','Seizure risk and interacting medications assessed']},
  {title:'Mood Stabilizer Monitoring',icon:FlaskConical,items:['Lithium: level, SCr/eGFR, TSH, calcium, hydration/interactions','Valproate: level, LFTs, CBC/platelets, sedation/tremor/weight','Carbamazepine: CBC, LFTs, sodium, interactions, rash risk','Lamotrigine: titration schedule, rash/SJS counseling, missed-dose restart rules','Pregnancy-related risk considered when clinically relevant']},
  {title:'Agitation/PRN Review',icon:Brain,items:['PRN frequency suggests need to reassess scheduled therapy?','Multiple PRNs with same purpose?','IM antipsychotic + benzodiazepine safety per facility protocol?','Sedation/respiratory depression/fall risk reviewed?','EPS prophylaxis or treatment needed?','QT and electrolyte risk reviewed?']}
];
const templates = [
  ['QT Risk Recommendation','Recommend evaluating QT risk due to current psychotropic regimen and patient-specific risk factors. Consider EKG and correction of potassium/magnesium if clinically appropriate.'],
  ['Metabolic Monitoring Recommendation','Recommend metabolic monitoring for antipsychotic therapy, including weight/BMI, blood pressure, glucose or A1c, and lipid panel per facility protocol.'],
  ['EPS Monitoring Recommendation','Recommend monitoring for extrapyramidal symptoms, akathisia, dystonia, and parkinsonism, especially given antipsychotic dose burden and/or recent medication changes.'],
  ['Sedation/Fall Risk Recommendation','Recommend reviewing cumulative CNS depressant burden and monitoring for sedation, orthostasis, and fall risk. Consider dose timing or regimen simplification if clinically appropriate.'],
  ['Lithium Safety Recommendation','Recommend lithium level with renal and thyroid monitoring, review of interacting medications, hydration status assessment, and monitoring for tremor, GI symptoms, confusion, or ataxia.'],
  ['Clozapine Safety Recommendation','Recommend verifying ANC eligibility and clozapine monitoring requirements, assessing bowel function, reviewing smoking status, and monitoring for sedation, orthostasis, metabolic effects, myocarditis warning signs, and seizure risk.']
].map(([title,body])=>({title,body}));
function Button({children,onClick,active}){return <button onClick={onClick} className={active?'btn active':'btn'}>{children}</button>}
function Badge({children}){return <span className="badge">{children}</span>}
function SectionHeader({icon:Icon,title,subtitle}){return <div className="section"><div className="icon"><Icon size={20}/></div><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div></div>}
function MedCard({med,favorites,toggleFavorite}){return <div className="card"><div className="cardtop"><div><h3>{med.name}</h3><p>{med.class}</p></div><button className="star" onClick={()=>toggleFavorite(med.name)}>{favorites.includes(med.name)?<Star size={20} fill="currentColor"/>:<StarOff size={20}/>}</button></div><div className="badges">{med.tags.map(t=><Badge key={t}>{t}</Badge>)}</div><h4>Clinical pearls</h4><ul>{med.pearls.map((p,i)=><li key={i}>{p}</li>)}</ul><h4>Monitoring</h4><div className="badges">{med.monitoring.map(t=><Badge key={t}>{t}</Badge>)}</div><h4 className="redtitle">Red flags</h4><div className="badges">{med.redFlags.map(t=><span key={t} className="redbadge">{t}</span>)}</div><div className="note">{med.note}</div></div>}
function App(){
 const [tab,setTab]=useState('meds'),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[favorites,setFavorites]=useState([]),[copied,setCopied]=useState('');
 const filtered=useMemo(()=>{const q=query.toLowerCase();return meds.filter(m=>(category==='All'||m.category===category)&&[m.name,m.class,m.category,...m.tags,...m.pearls,...m.monitoring,...m.redFlags].join(' ').toLowerCase().includes(q))},[query,category]);
 const toggleFavorite=name=>setFavorites(prev=>prev.includes(name)?prev.filter(x=>x!==name):[...prev,name]);
 const copyText=async(t,b)=>{try{await navigator.clipboard.writeText(b);setCopied(t);setTimeout(()=>setCopied(''),1800)}catch{setCopied('Copy unavailable')}};
 return <div className="app"><main><header><div className="brand"><Pill/><h1>BH Pharm</h1></div><span>Pocket Guide</span><p>Privacy-safe behavioral health pharmacy workflow support. Avoid entering patient names, DOBs, MRNs, or other PHI.</p></header><nav><Button active={tab==='meds'} onClick={()=>setTab('meds')}>Meds</Button><Button active={tab==='lai'} onClick={()=>setTab('lai')}>LAIs</Button><Button active={tab==='checks'} onClick={()=>setTab('checks')}>Checks</Button><Button active={tab==='notes'} onClick={()=>setTab('notes')}>Notes</Button></nav>{tab==='meds'&&<><SectionHeader icon={Search} title="Psych Med Search" subtitle="Fast pearls, monitoring, and note language"/><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search clozapine, QT, ANC, EPS..."/></div><div className="chips">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={category===c?'chip chipactive':'chip'}>{c}</button>)}</div><div>{filtered.map(m=><MedCard key={m.name} med={m} favorites={favorites} toggleFavorite={toggleFavorite}/>)}</div></>}{tab==='lai'&&<><SectionHeader icon={Pill} title="LAI Quick Check" subtitle="Verify product, timing, overlap, and missed-dose rules"/>{meds.filter(m=>m.category==='LAI').map(m=><div className="card" key={m.name}><h3>{m.name}</h3><p>{m.class}</p><div className="blue"><b>Before administration:</b> confirm exact product, last injection date, dose, site, initiation status, oral overlap need, renal considerations when relevant, and missed-dose instructions.</div>{m.monitoring.map((it,i)=><label className="check" key={i}><input type="checkbox"/> {it}</label>)}<h4 className="redtitle">Red flags</h4><div className="badges">{m.redFlags.map(t=><span key={t} className="redbadge">{t}</span>)}</div></div>)}</>}{tab==='checks'&&<><SectionHeader icon={ClipboardCheck} title="Checklists" subtitle="Use as a thinking aid, not a substitute for clinical judgment"/>{checklists.map(list=>{const Icon=list.icon;return <div className="card" key={list.title}><h3 className="row"><Icon size={20}/>{list.title}</h3>{list.items.map((item,i)=><label className="check" key={i}><input type="checkbox"/> {item}</label>)}</div>})}</>}{tab==='notes'&&<><SectionHeader icon={FileText} title="Consult Note Templates" subtitle="Tap copy, then customize before documenting"/>{templates.map(t=><div className="card" key={t.title}><div className="cardtop"><h3>{t.title}</h3><button className="small" onClick={()=>copyText(t.title,t.body)}>Copy</button></div><p className="bodytext">{t.body}</p>{copied===t.title&&<p className="copied">Copied.</p>}</div>)}</>}<footer><HeartPulse/><p><b>Safety note:</b> This prototype is for pharmacist workflow support only. Do not enter PHI. Verify recommendations against facility policy, current labeling, and clinical judgment.</p></footer></main></div>
}
createRoot(document.getElementById('root')).render(<App/>);
